---
title: "Testing methods for the genieric forest resilience model"
author: "Camille Piponiot"
date: Sys.Date()
output: html_document
---

```{r global_options, include=FALSE}
## install and load packages ##
packages_needed = c("data.table", "ggplot2", "entropart")
packages_to_install = packages_needed[!( packages_needed %in% rownames(installed.packages()))]
if (length(packages_to_install) > 0)
  install.packages(packages_to_install)
lapply(packages_needed, require, character.only = TRUE)
# library(rstan)
# rstan_options(auto_write = TRUE)
# options(mc.cores = parallel::detectCores())
# from github
if (!require(ForestData)){
  remotes::install_github("EcoFoG/ForestData")
}
```


## Prepare example data - Paracou

```{r load-data, cache=TRUE}
cache = TRUE
if (!cache) {
  paracou = read.csv2("data/paracou.csv")
  ## remove plot 16 (biodiversity plot)
  paracou = subset(paracou, as.numeric(n_parcelle) < 16)
  ## remove "mortality-only" censuses
  paracou = subset(paracou, !(campagne %in% c(1996, 1998, 2000, 2002)))
  ## one subplot (parcelle 15 carré 2) was forgotten in 2010
  paracou = subset(paracou, !(n_parcelle == 15 & campagne == 2010))
  
  #### (2) prepare and correct data with the ForestData package ###
  ## for now
  paracou$pom <- 1.3 #+ paracou$code_mesure*0.5
  # paracou$pom[paracou$code_mesure > 3] <- 1.3
  
  prepare_forestdata(paracou,
                     plot_col="n_parcelle",
                     id_col="i_arbre",
                     time_col="campagne", 
                     status_col = "code_vivant",
                     size_col="circonf",
                     measure_type = "C",
                     POM_col = "pom")
  setDT(paracou)
  paracou[, `:=`(Genre = Genre[which.max(campagne)], 
                 espece = espece[which.max(campagne)], 
                 Famille = Famille[which.max(campagne)], 
                 x = x[which.max(campagne)], 
                 y = y[which.max(campagne)]), .(i_arbre)]
  
  paracou$espece_1 <- tstrsplit(paracou$espece, " ")[[1]]
  paracou$binomial_name <- paste(paracou$Genre, paracou$espece_1)
  
  data <- correct_alive(paracou,
                        invariant_columns = c("Genre",
                                              "espece",
                                              "Famille",
                                              "NomForet", 
                                              "binomial_name",
                                              "n_carre",
                                              "x", "y"))
  prepare_forestdata(data,
                     plot_col="n_parcelle",
                     id_col="i_arbre",
                     time_col="campagne",
                     status_col = "status_corr",
                     size_col="circonf",
                     measure_type = "C",
                     POM_col = "pom")
  
  ldata = lapply(1:14, function(i){
    rbindlist(lapply(1:4, function(j) {
      correct_size(subset(data, n_parcelle==i & n_carre==j))
    }))
  })
  datac = rbindlist(ldata)
  data_corr <- correct_recruits(datac,
                                invariant_columns = c("Genre",
                                                      "espece",
                                                      "Famille",
                                                      "NomForet",
                                                      "binomial_name",
                                                      "n_carre",
                                                      "x", "y"))
  # table(data_corr$code_corr)
  # ggplot(data_corr[i_arbre %in% unique(subset(data_corr, code_corr!=0)$i_arbre)[1:20]], aes(x=campagne)) + 
  #   geom_point(aes(y=size_corr), col=2) + geom_point(aes(y=circonf), col=1) + facet_wrap(~i_arbre, scale="free")
  
  save(data_corr, file = "cache/data_corr.rda")
} else 
  load("cache/data_corr.rda")

## Calculate ecosystem variables --------------------------------

# get aboveground biomass
data_corr$wd = BIOMASS::getWoodDensity(genus = data_corr$Genre, species = data_corr$espece_1)$meanWD
data_corr$agb = BIOMASS::computeAGB(D = data_corr$size_corr/pi, WD = data_corr$wd, coord = c(-52.88, 5.3))

gini = function(x) { ## gini index: measure of the 
  y = sort(x)
  n = length(y)
  return(2/n*sum(seq_len(n)*y)/sum(y) - (n+1)/n)
}

if (!file.exists("cache/dfvar.rda")) {
  dfvar = data_corr[, .(agb = sum(agb)/(6.25/4), 
                        n = as.numeric(length(i_arbre)), 
                        qmd = sqrt(sum((size_corr/pi)**2)/length(i_arbre)), 
                        gini = gini(size_corr),
                        rich = bcDiversity(Ns = data.frame(table(binomial_name))$Freq, q = 0), 
                        shan = bcDiversity(Ns = data.frame(table(binomial_name))$Freq, q = 1), 
                        simp = bcDiversity(Ns = data.frame(table(binomial_name))$Freq, q = 2)), 
                    .(plot = n_parcelle, subplot = n_carre, year = campagne)]
  
  save(dfvar, file = "cache/dfvar.rda")
} else 
  load("cache/dfvar.rda")
```

## Reduce dimensions

```{r reduce-corr}
dfvar$rich = NULL
corrplot::corrplot(cor(dfvar[, 4:9]))
source("R/choose_vars.R")
choose_vars(as.matrix(dfvar[, 4:9]), 3, 0.3) ## chooses N trees, gini index (can use AGB instead, highly correlated), and Shannon diversity

# pca_df = prcomp(dfvar[, 4:9])
# autoplot(pca_df, loadings = TRUE, loadings.label = TRUE)

corrplot::corrplot(cor(dfvar[, c(4, 5, 8)]),
                   type = "lower",
                   method = "number", 
                   diag = FALSE)
```

```{r plot3, fig.width = 12, fig.height = 4}
treat = data.table(plot = as.character(1:14), treat = c(0:3, 2, 0, 1, 3, 1, 2, 0, 3, 0, 0))
dfvar = merge(dfvar, treat, by = "plot")

dfmelt = melt(dfvar[,c(1:5, 8, 10)], id.vars = c("plot", "subplot", "year", "treat"))
ggplot(dfmelt, aes(x = year, y = value, color = as.factor(treat), group = paste(plot, subplot))) + 
  geom_line() + geom_point() + 
  facet_wrap(~ variable, scales = "free")
```


```{r, fig.width = 12, fig.height = 4}
g1 = ggplot(dfvar[year >=1990], aes(x = agb, y = n, color = as.factor(treat), group = paste(plot, subplot))) + 
  geom_line() + geom_point() + 
  geom_point(data = dfvar[year == 1990], size = 4) + 
  theme(legend.position = "none")
g2 = ggplot(dfvar[year >=1990], aes(x = agb, y = shan, color = as.factor(treat), group = paste(plot, subplot))) + 
  geom_line() + geom_point() + 
  geom_point(data = dfvar[year == 1990], size = 4) + 
  theme(legend.position = "none")
g3 = ggplot(dfvar[year >=1990], aes(x = n, y = shan, color = as.factor(treat), group = paste(plot, subplot))) + 
  geom_line() + geom_point() + 
  geom_point(data = dfvar[year == 1990], size = 4) + 
  theme(legend.position = "none")
ggpubr::ggarrange(g1, g2, g3, nrow = 1)
``` 

## Exploring differential equations for AGB and N

```{r rate-of-change}
setorder(dfvar, plot, subplot, year)
dfvar[, `:=`(dndt = c(NA, diff(n)/diff(year)), 
             dagbdt = c(NA, diff(agb)/diff(year))), 
      .(plot, subplot)]
dfvar$group_agb = cut(dfvar$n, breaks = 5)
dfvar$group_n = cut(dfvar$agb, breaks = 5)

df1 = melt(dfvar, id.vars = c("plot", "subplot", "year", "treat"), 
           measure.vars = grep("group", colnames(dfvar)), value.name = "group")
df1$variable = gsub("group_", "", df1$variable)
df2 = melt(dfvar, id.vars = c("plot", "subplot", "year", "treat", "dndt", "dagbdt"), 
           measure.vars = c("agb", "n"))
df2b = melt(df2, id.vars = c("plot", "subplot", "year", "treat", "variable", "value"), 
            measure.vars = c("dndt", "dagbdt"), variable.name = "vardiff", value.name = "dxdt")
dfdiff = merge(df1, df2b, by = c("plot", "subplot", "year", "treat", "variable"))

dfdiff = subset(dfdiff, year > 1990)
```

```{r plot-diffs, fig.width = 12, fig.height = 10}
ggplot(dfdiff, aes(x = value, y = dxdt, color = group)) + 
  geom_point() + 
  geom_hline(yintercept = 0, lty=2) +
  geom_smooth() + 
  facet_grid(vardiff ~ variable, scales = "free")
```


### Build model 


$$\frac{dN}{dt} = r_{1} N  (1-\frac{N}{K_1} + \frac{\alpha_1 AGB}{K_1} )$$

$$\frac{dAGB}{dt} = r_2 AGB (1-\frac{AGB}{K_2} + \frac{\alpha_{2} N}{K_2})$$

```{r simulations-simple-model}
library(deSolve)

time <- seq(0, 100, by = 1)
df0 <- expand.grid(n = c(800, 1000, 1200), 
                   agb = c(150, 200, 300), 
                   r_n = 0.1, 
                   K_n = 1000, 
                   a_n = c(-0.5, 0, 0.5), 
                   r_b = 0.005, 
                   K_b = 200, 
                   a_b = c(-0.5, 0, 0.5))

# p <- c()

model_logistic_expl <- function(t, y, p) {
  n <- y[1]
  agb <- y[2]
  dn_dt <-   p[1] * n   * (1 - n   / p[2] + p[3] / p[2] * agb ) 
  dagb_dt <- p[4] * agb * (1 - agb / p[5] + p[6] / p[5] * n   )
  return(list(c(dn_dt, dagb_dt)))
}

dyn_t <-
  lapply(seq_len(nrow(df0)), function(i)
    data.table(ode(y = unlist(df0[i, c("n", "agb")]), 
                   times = time, model_logistic_expl, 
                   unlist(df0[i, c("r_n", "K_n", "a_n", 
                                   "r_b", "K_b", "a_b")]))))
dyn_t <- rbindlist(dyn_t, idcol = "simu")

colnames(df0)[1:2] = c("n0", "agb0")
df0$simu = seq_len(nrow(df0))
dyn_t <- merge(dyn_t, df0)
dyn_t$simu_name <- paste("agb0 =", dyn_t$agb0, "; n0 =", dyn_t$n0)

ggplot(dyn_t, aes(x = time, y = n, color = simu_name)) + 
  geom_line() + 
  facet_grid(paste("a_n =", a_n) ~ paste("a_b =", a_b))
ggplot(dyn_t, aes(x = time, y = agb, color = simu_name)) + 
  geom_line() + 
  facet_grid(paste("a_n =", a_n) ~ paste("a_b =", a_b))
ggplot(dyn_t, aes(x = agb, y = n, color = simu_name)) + 
  geom_line() + 
  geom_point(data = subset(dyn_t, time == 0)) + 
  facet_grid(paste("a_n =", a_n) ~ paste("a_b =", a_b))
```


### Fit stan model

```{r stan-diffeq}
if (!file.exists("stan/fit_simple-model_agb-n.rda")) {
  library(rstan)
  options(mc.cores = parallel::detectCores())
  rstan_options(auto_write = TRUE)
  
  dfvar_post = subset(dfvar, !is.na(dndt) & !(year < 1990 & treat > 0))
  data = list(
    N = nrow(dfvar_post),
    dndt = dfvar_post$dndt,
    dbdt = dfvar_post$dagbdt,
    n = dfvar_post$n,
    b = dfvar_post$agb
  )
  
  simple_model = stan(file = "stan/simple-model_agb-n.stan", data = data)
  traceplot(simple_model)
  save(simple_model, file = "stan/fit_simple-model_agb-n.rda")
} else {
  load("stan/fit_simple-model_agb-n.rda")
}
```


### Observations vs predictions


```{r gof1-simple-model}
time <- seq(0, 100, by = 1)
y0 <- expand.grid(n = c(800, 1000, 1200), 
                  agb = c(150, 200, 300))

pars_stan = rstan::extract(simple_model)
maxl = which.max(pars_stan$lp__)
p <- c(r_n = pars_stan$r_n[maxl], 
       K_n = pars_stan$K_n[maxl], 
       a_n = pars_stan$a_n[maxl], 
       r_b = pars_stan$r_b[maxl], 
       K_b = pars_stan$K_b[maxl], 
       a_b = pars_stan$a_b[maxl])

dyn_t <-
  lapply(seq_len(nrow(y0)), function(i)
    data.table(ode(y = unlist(y0[i,]), times = time, model_logistic_expl, p)))
dyn_t <- rbindlist(dyn_t, idcol = "simu")

colnames(y0) = c("n0", "agb0")
y0$simu = seq_len(nrow(y0))
dyn_t <- merge(dyn_t, y0)
dyn_t$simu_name <- paste("agb0 =", dyn_t$agb0, "; n0 =", dyn_t$n0)

ggplot(dyn_t, aes(x = time, y = n, color = simu_name)) + 
  geom_line()
ggplot(dyn_t, aes(x = time, y = agb, color = simu_name)) + 
  geom_line()
ggplot(dyn_t, aes(x = agb, y = n, color = simu_name)) + 
  geom_line() + 
  geom_point(data = subset(dyn_t, time == 0))
```

```{r obs-vs-simulations-simple-model, fig.height = 12, fig.width = 10}
dfsub = subset(dfvar, !is.na(dndt) & !(year <= 1990 & treat > 0))
df0 = dfsub[, .(year = min(year), tmax = diff(range(year))), .(plot, subplot)]
df0 = merge(df0, dfvar[, c("plot", "subplot", "year", "n", "agb")], 
            by = c("plot", "subplot", "year"))
df0$idplot = paste(df0$plot, df0$subplot, sep = "_")

dyn_t <-
  lapply(seq_len(nrow(df0)), function(i)
    data.table(ode(y = unlist(df0[i, c("n", "agb")]), 
                   times = seq(0, df0$tmax[i], by = 1), 
                   model_logistic_expl, p)))
names(dyn_t) <- df0$idplot
dyn_t <- rbindlist(dyn_t, idcol = "idplot")

colnames(df0)[colnames(df0) %in% c("n", "agb")] <- 
  paste0(colnames(df0)[colnames(df0) %in% c("n", "agb")], 0)
dyn_t <- merge(dyn_t, df0, by = "idplot")

ggplot(dyn_t, aes(x = agb, y = n, color = as.factor(subplot))) + 
  geom_line() + 
  geom_point(data = subset(dyn_t, time == 0), shape = 3) + 
  geom_point(data = dfsub) +
  facet_wrap(~ plot, scales = "free")
```

```{r}
dfsub[, time := year - min(year)]
dfobs = melt(dfsub, id.vars = c("plot", "subplot", "time", "treat"), 
             measure.vars = c("n", "agb", "dndt", "dagbdt"), value.name = "obs")

dfpred = melt(dyn_t, id.vars = c("plot", "subplot", "time"), 
             measure.vars = c("n", "agb"), value.name = "pred")
dfsub$p_dndt = p[1] * dfsub$n   * (1 - dfsub$n   / p[2] + p[3] / p[2] * dfsub$agb )
dfsub$p_dagbdt = p[4] * dfsub$agb * (1 - dfsub$agb / p[5] + p[6] / p[5] * dfsub$n ) 
dfpred2 = melt(dfsub, id.vars = c("plot", "subplot", "time"), 
             measure.vars = c("p_dndt", "p_dagbdt"), value.name = "pred")
dfpred2$variable = gsub("p_", "", dfpred2$variable)
dfpred = rbind(dfpred, dfpred2)
  
dfgof = merge(dfpred, dfobs)

ggplot(dfgof, aes(x = obs, y = pred, color = as.factor(treat))) +
  geom_point() + 
  geom_abline(intercept = 0, slope = 1, lty = 2) +
  facet_wrap(~ variable, scales = "free")
```


